### ISSUE TITLE
Cannot process windows ar files

### ISSUE THREAD

**Issue by pombredanne** [viraptor/arpy#9]
The htmlhelp.lib AR file included in http://download.microsoft.com/download/0/A/9/0A939EF6-E31C-430F-A3DF-DFAE7960D564/helpdocs.zip
(from https://msdn.microsoft.com/en-us/library/windows/desktop/ms669985%28v=vs.85%29.aspx )
fails to extract (note that it also contains symbol table most likely)

```
>>> import arpy
>>> ar = arpy.Archive('x/htmlhelp.lib')
>>> ar.read_all_headers()
Traceback (most recent call last):
  File "/tmp/tk/lib/python3.6/site-packages/arpy.py", line 106, in __init__
    self.uid = int(uid)
ValueError: invalid literal for int() with base 10: b'      '

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/tk/lib/python3.6/site-packages/arpy.py", line 342, in read_all_headers
    while self.read_next_header() is not None:
  File "/tmp/tk/lib/python3.6/site-packages/arpy.py", line 320, in read_next_header
    header = self.__read_file_header(self.next_header_offset)
  File "/tmp/tk/lib/python3.6/site-packages/arpy.py", line 243, in __read_file_header
    file_header = ArchiveFileHeader(header, offset)
  File "/tmp/tk/lib/python3.6/site-packages/arpy.py", line 112, in __init__
    "cannot convert file header fields to integers", err)
arpy.ArchiveFormatError: ('cannot convert file header fields to integers', ValueError("invalid literal for int() with base 10: b' 
  '",))

```

**Comment by viraptor** [comment]
Hmm... I'm not sure what that file even is. My system's ar is not able to list the contents.
I'll investigate some more.

**Comment by viraptor** [comment]
@pombredanne Did you want to read something specific from that file? I can certainly mark this header as "weird windowsy thing" and skip it. At least I don't crash in that case :) If you know where to find more info, I could maybe do something more creative...

**Comment by viraptor** [comment]
Ok, I see what's happening. Windows doesn't do things like uid and gid, so they will need to be None.
PR incoming.

**Comment by viraptor** [comment]
@pombredanne let me know if the linked PR solves the issues for you.

**Comment by pombredanne** [comment]
@viraptor that was quick! let me test that ASAP
FWIW I keep a bunch of ar test files there https://github.com/nexB/scancode-toolkit/tree/develop/tests/extractcode/data/archive/ar
there https://github.com/nexB/scancode-toolkit/tree/develop/tests/extractcode/data/archive/weird_names and there https://github.com/nexB/scancode-toolkit/tree/develop/tests/extractcode/data/archive/ar/winlib

**Comment by pombredanne** [comment]
It works for that archive but I am not 100% sure this is correct as windows ar lib may contain more than one entry with the same name and you track these in a dict keys by path so there cannot be more than one file at the same path in your model... is this true? I think it is per https://github.com/viraptor/arpy/blob/1437531491916873e06083a973952284cb737fd1/arpy.py#L207

Also these archives are not processed OK:

- https://github.com/nexB/scancode-toolkit/blob/develop/tests/extractcode/data/archive/ar/winlib/freetype.lib

- https://github.com/nexB/scancode-toolkit/blob/develop/tests/extractcode/data/archive/weird_names/weird_names.ar

- https://github.com/nexB/scancode-toolkit/blob/develop/tests/extractcode/data/archive/ar/winlib/gsdll32.lib seems fine but there are more than one file entries there.

**Comment by viraptor** [comment]
The files dict is there for convenience, but if you have special cases, you can handle them directly:
```
ar = arpy.Archive...
ar.read_all_headers()
for header in ar.headers:
  if header.type in (arpy.HEADER_BSD, arpy.HEADER_NORMAL, arpy.HEADER_GNU):
    filename = header.name
    content = arpy.ArchiveFileData(ar_obj: ar, header: header)
```
it works with repeated file names too. I guess it's not an amazing interface though. Any suggestions that don't break the current interface?

**Comment by pombredanne** [comment]
Thanks! 

And you wrote:
> I guess it's not an amazing interface though. Any suggestions that don't break the current interface?

My suggestion would be to let the existing API as-is and craft a new class that would use the same API as the standard lib zipfile/tarfile e.g. hide the use of `read_all_headers()` and does the right thing by default handling all header types.

**Comment by pombredanne** [comment]
Vaguely related you may be interested to peek into that lesser-known and now-abandoned ar implementation used in Chromium, possibly for its tests?

 https://chromium.googlesource.com/infra/luci/luci-py/+/650536bb4b4c8b1a6ecd58deb80df8be200fc19d/client/libs/arfile/

**Comment by viraptor** [comment]
Hmmm... how I wonder if I can register myself to the zipfile interface and just let it handle most things.
But even if I can't, I could certainly reuse the idea dual access via name or info.

**Comment by viraptor** [comment]
Oops, I read it as zipfile supporting multiple formats, but actually it just supports multiple compressions in zip. I'll have to reuse the idea rather than the interface.

**Comment by pombredanne** [comment]
> I'll have to reuse the idea rather than the interface.

Yes this is what I meant: having a similar and familiar API, not reusing the code itself

**Comment by viraptor** [comment]
Added in https://github.com/viraptor/arpy/pull/11
